name: Generate and Commit API Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate API Documentation
        run: |
          # This command generates the documentation.
          # You can add AI enhancement flags here, for example:
          # Apimatic generate --src . --use-openai --openai-model gpt-4o-mini
          Apimatic generate --src . --output API_Docs.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update generated API documentation"
          file_pattern: API_Docs.md
