name: Generate API Docs

on:
  push:
    branches: [ "main" ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install autodoc-gen
        run: pip install .
        
      - name: Generate Markdown
        run: |
          autodoc-gen --src . --format markdown --output API_Docs.md || true
          
      - name: Generate OpenAPI
        run: |
          python -c "import yaml" 2>/dev/null || pip install pyyaml
          autodoc-gen --src . --format openapi --output openapi.yaml || true
          
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add API_Docs.md openapi.yaml || true
          git diff --cached --quiet && echo "No changes" || git commit -m "chore(docs): update API docs [auto]"
          git push || true
